// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Importante: este arquivo é carregado por TODO comando do Prisma,
// inclusive "generate" — que não precisa de conexão real com o
// banco, só do schema. Por isso NÃO travamos aqui se DATABASE_URL
// estiver ausente (ex: durante o passo de instalação de
// dependências na Vercel, antes das env vars da build ficarem
// visíveis). Comandos que realmente precisam do banco ("migrate
// deploy", "db seed" etc.) vão falhar com o próprio erro claro do
// Prisma se a URL estiver mesmo faltando ou errada.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
